caseSensitive: false
wholeWordsOnly: true
excludeTags: ["h1", "h2", "h3", "h4", "h5", "h6", "a"]
useTaxonomyValues: true

replacements: 
  - keywords: ["condation", "CondationCMS"]
    link: https://condation.com